model:
  path: Llama-3.2-3B-Instruct
  prompt_path: prompts/mind_title.txt
  freeze_lora: True
  max_txt_len: 256
  ckpt: 
  use_item_embedding: False # True: use item embedding, False: use item title

dataset:
  name: MIND
  train: datasets/MIND/train_sampled_50k.tsv
  valid: datasets/MIND/valid_sampled_50k.tsv
  user_dict: datasets/MIND/user_dict_mind.pickle

run:
  seed: 42
  evaluate: True # False: training, True: only evaluation 
  output_dir: outputs
  device: cuda
  init_lr: 8e-4
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 48
  max_epoch: 15
  norm_lambda: 0.2
  resume_ckpt_path: null
  min_epoch: 8
  lr_scheduler: cosine #"linear", "cosine", "cosine_with_restarts", "polynomial", "constant", "constant_with_warmup"
  num_warmup_steps: 0
  gradient_accumulation_steps: 1
